#!/bin/bash

set -e

# Configuration - use environment variables
AWS_REGION=${AWS_REGION:-"your-aws-region"}
AWS_PROFILE=${AWS_PROFILE:-"default"}
REPOSITORY_NAME="prequel-dev-code-server"

# Get account ID using current AWS configuration
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
ECR_URI="${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPOSITORY_NAME}"

echo "Building code-server Docker image..."
echo "Repository: $ECR_URI"

# Login to ECR
echo "Logging in to ECR..."
aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI

# Build and push the Docker image for AMD64 (ECS Fargate architecture)
echo "Building and pushing Docker image..."
docker buildx build --platform=linux/amd64 -t "$ECR_URI:latest" --push .

echo ""
echo "✅ Code-server image built and pushed successfully!"
echo "Image URI: $ECR_URI:latest"
echo ""
echo "🚀 SOCI index will be automatically generated by AWS Lambda after push!"