#!/bin/bash

# Build and push code-server Docker image with SOCI-compatible compression
#
# Usage: ./build-and-push.sh [environment]
#   environment: dev, prod, or staging (optional, defaults to ENVIRONMENT from .env.local)
#
# This script builds the code-server image using zstd-variant of eStargz compression,
# which is compatible with AWS SOCI (Seekable OCI) indexing for faster container startup.
#
# Why zstd-variant eStargz?
# - Standard zstd compression is not compatible with SOCI indexing
# - zstd-variant of eStargz provides both zstd compression benefits and seekability
# - This enables lazy loading of container layers and faster startup times

set -e

# Load environment variables from .env.local (check root directory)
if [ ! -f ../.env.local ]; then
	echo "Error: .env.local file not found in project root"
	echo "Please copy .env.example to .env.local and configure your environment variables"
	exit 1
fi

export $(cat ../.env.local | grep -v '^#' | sed 's/#.*//' | grep -v '^$' | xargs)

# Allow environment override from command line
TARGET_ENV=${1:-$ENVIRONMENT}

# Configuration - use environment variables
AWS_REGION=${AWS_REGION}
AWS_PROFILE=${AWS_PROFILE}
REPOSITORY_NAME="${PROJECT_PREFIX}-${TARGET_ENV}-code-server"

echo "Building for environment: $TARGET_ENV"

# Get account ID using current AWS configuration
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
ECR_URI="${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPOSITORY_NAME}"

echo "Building code-server Docker image..."
echo "Repository: $ECR_URI"

# Login to ECR
echo "Logging in to ECR..."
aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI

# Build and push the Docker image for AMD64 (ECS Fargate architecture) with SOCI-compatible compression
echo "Building and pushing Docker image with SOCI-compatible compression..."

# Variable to track which compression was used
COMPRESSION_USED=""

# Try zstd-variant eStargz first
echo "🔄 Attempting build with zstd-variant eStargz compression..."
set +e # Temporarily disable exit on error for testing
docker buildx build \
	--platform=linux/amd64 \
	--output type=image,name="$ECR_URI:latest",push=true,compression=zstd:estargz,force-compression=true,oci-mediatypes=true \
	.
ZSTD_RESULT=$?
set -e # Re-enable exit on error

if [ $ZSTD_RESULT -eq 0 ]; then
	echo "✅ Built with zstd-variant eStargz compression"
	COMPRESSION_USED="zstd-variant eStargz"
else
	echo "❌ zstd-variant eStargz failed, trying standard eStargz..."

	set +e # Temporarily disable exit on error for testing
	docker buildx build \
		--platform=linux/amd64 \
		--output type=image,name="$ECR_URI:latest",push=true,compression=estargz,force-compression=true,oci-mediatypes=true \
		.
	ESTARGZ_RESULT=$?
	set -e # Re-enable exit on error

	if [ $ESTARGZ_RESULT -eq 0 ]; then
		echo "✅ Built with standard eStargz compression (gzip-based)"
		COMPRESSION_USED="standard eStargz (gzip-based)"
	else
		echo "❌ eStargz failed, building with gzip compression for SOCI compatibility..."
		docker buildx build \
			--platform=linux/amd64 \
			--output type=image,name="$ECR_URI:latest",push=true,compression=gzip,oci-mediatypes=true \
			.
		echo "✅ Built with gzip compression (SOCI compatible)"
		COMPRESSION_USED="gzip (SOCI compatible)"
	fi
fi

echo ""
echo "✅ Code-server image built and pushed successfully with SOCI-compatible compression!"
echo "Image URI: $ECR_URI:latest"
echo "📦 Compression: $COMPRESSION_USED"
echo ""
echo "🚀 SOCI index will be automatically generated by AWS Lambda after push!"
echo "💡 This image format is optimized for lazy loading and SOCI indexing."
